#!/bin/python

import os,sys

print sys.argv

f = open('/tmp/test.dat', 'w')
f.write("\n")
for i in range(1,1+len(sys.argv)/2):
    f.write(str(sys.argv[i*2-1]) + " " + str(sys.argv[i*2]) + "\n")
f.close()

code = """
set style line 1 lc rgb '#0060ad' lt 1 lw 2 pt 7 ps 1.5
set xdata time
set timefmt '%Y-%m'
set grid
set xtics format '%Y-%m'
plot [:][:] '/tmp/test.dat' using 1:2 with linespoints ls 1
"""

os.system("gnuplot --persist -e \"" + ";".join(code.split("\n")) + "\"")

